import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layout/Navbar";
import { GameProvider } from '../lib/GameContext';
import BootstrapUser from "@/components/BootstrapUser";
import BetaModal from "@/components/BetaModal";
import Footer from "@/components/layout/Footer";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="flex min-h-screen flex-col mt-[96px] lg:mt-[116px] max-w-[1326px] mx-auto">
        <BootstrapUser />
        <BetaModal />
        <GameProvider>
          <Navbar />
          <main className="flex-1 w-full">{children}</main>
          <Footer />
        </GameProvider>
      </body>
    </html>
  );
}